name: MMBC Battery Controller
version: "0.3.0"
slug: mmbc
description: Multiple Marstek Battery Controller for Home Assistant
startup: services
boot: auto
image: "vmangelschots/mmbc:0.3.0"
host_network: true
privileged: []
options: {}
schema: {}